/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ScheduleIntervalService } from "../scheduleInterval.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ScheduleIntervalCreateInput } from "./ScheduleIntervalCreateInput";
import { ScheduleIntervalWhereInput } from "./ScheduleIntervalWhereInput";
import { ScheduleIntervalWhereUniqueInput } from "./ScheduleIntervalWhereUniqueInput";
import { ScheduleIntervalFindManyArgs } from "./ScheduleIntervalFindManyArgs";
import { ScheduleIntervalUpdateInput } from "./ScheduleIntervalUpdateInput";
import { ScheduleInterval } from "./ScheduleInterval";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ScheduleIntervalControllerBase {
  constructor(
    protected readonly service: ScheduleIntervalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ScheduleInterval })
  @nestAccessControl.UseRoles({
    resource: "ScheduleInterval",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: ScheduleIntervalCreateInput
  ): Promise<ScheduleInterval> {
    return await this.service.create({
      data: {
        ...data,

        daySchedule: data.daySchedule
          ? {
              connect: data.daySchedule,
            }
          : undefined,
      },
      select: {
        category: true,
        createdAt: true,

        daySchedule: {
          select: {
            id: true,
          },
        },

        end: true,
        id: true,
        label: true,
        start: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ScheduleInterval] })
  @ApiNestedQuery(ScheduleIntervalFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ScheduleInterval",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<ScheduleInterval[]> {
    const args = plainToClass(ScheduleIntervalFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        category: true,
        createdAt: true,

        daySchedule: {
          select: {
            id: true,
          },
        },

        end: true,
        id: true,
        label: true,
        start: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ScheduleInterval })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ScheduleInterval",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: ScheduleIntervalWhereUniqueInput
  ): Promise<ScheduleInterval | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        category: true,
        createdAt: true,

        daySchedule: {
          select: {
            id: true,
          },
        },

        end: true,
        id: true,
        label: true,
        start: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ScheduleInterval })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ScheduleInterval",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: ScheduleIntervalWhereUniqueInput,
    @common.Body() data: ScheduleIntervalUpdateInput
  ): Promise<ScheduleInterval | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          daySchedule: data.daySchedule
            ? {
                connect: data.daySchedule,
              }
            : undefined,
        },
        select: {
          category: true,
          createdAt: true,

          daySchedule: {
            select: {
              id: true,
            },
          },

          end: true,
          id: true,
          label: true,
          start: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ScheduleInterval })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ScheduleInterval",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: ScheduleIntervalWhereUniqueInput
  ): Promise<ScheduleInterval | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          category: true,
          createdAt: true,

          daySchedule: {
            select: {
              id: true,
            },
          },

          end: true,
          id: true,
          label: true,
          start: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
